# Generated by Django 4.0.4 on 2022-06-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_role', '0003_alter_otp_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr_profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='hr_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
