# Generated by Django 4.0.4 on 2022-05-31 10:40

import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ques_option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('ques_images1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ques_images2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ques_images3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ques_images4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ans', models.TextField()),
                ('option_type', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('editby_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamplePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_url', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
