# Generated by Django 4.0.4 on 2022-05-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_role', '0001_initial'),
        ('Product_owner_role', '0001_initial'),
        ('Sample_Paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_record',
            name='interviewee_TestDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_role.intervieweetestdetails'),
        ),
        migrations.AddField(
            model_name='test_record',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.question'),
        ),
        migrations.AddField(
            model_name='test_record',
            name='sample_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.samplepaper'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_owner_role.tasklanguage'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_owner_role.tasklevel'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='ques_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.question_type'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='Sample_Paper.question'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_role.company_profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='addedby_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_role.company_profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product_owner_role.tasklanguage'),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product_owner_role.tasklevel'),
        ),
        migrations.AddField(
            model_name='question',
            name='ques_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.question_type'),
        ),
    ]
